// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CustomPrintFormDetection.proto

package Diadoc.Api.Proto;

public final class CustomPrintFormDetection {
  private CustomPrintFormDetection() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface CustomPrintFormDetectionRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Diadoc.Api.Proto.CustomPrintFormDetectionRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .Diadoc.Api.Proto.DocumentId DocumentIds = 1;</code>
     */
    java.util.List<Diadoc.Api.Proto.DocumentIdOuterClass.DocumentId> 
        getDocumentIdsList();
    /**
     * <code>repeated .Diadoc.Api.Proto.DocumentId DocumentIds = 1;</code>
     */
    Diadoc.Api.Proto.DocumentIdOuterClass.DocumentId getDocumentIds(int index);
    /**
     * <code>repeated .Diadoc.Api.Proto.DocumentId DocumentIds = 1;</code>
     */
    int getDocumentIdsCount();
    /**
     * <code>repeated .Diadoc.Api.Proto.DocumentId DocumentIds = 1;</code>
     */
    java.util.List<? extends Diadoc.Api.Proto.DocumentIdOuterClass.DocumentIdOrBuilder> 
        getDocumentIdsOrBuilderList();
    /**
     * <code>repeated .Diadoc.Api.Proto.DocumentId DocumentIds = 1;</code>
     */
    Diadoc.Api.Proto.DocumentIdOuterClass.DocumentIdOrBuilder getDocumentIdsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code Diadoc.Api.Proto.CustomPrintFormDetectionRequest}
   */
  public static final class CustomPrintFormDetectionRequest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Diadoc.Api.Proto.CustomPrintFormDetectionRequest)
      CustomPrintFormDetectionRequestOrBuilder {
    // Use CustomPrintFormDetectionRequest.newBuilder() to construct.
    private CustomPrintFormDetectionRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private CustomPrintFormDetectionRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final CustomPrintFormDetectionRequest defaultInstance;
    public static CustomPrintFormDetectionRequest getDefaultInstance() {
      return defaultInstance;
    }

    public CustomPrintFormDetectionRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private CustomPrintFormDetectionRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                documentIds_ = new java.util.ArrayList<Diadoc.Api.Proto.DocumentIdOuterClass.DocumentId>();
                mutable_bitField0_ |= 0x00000001;
              }
              documentIds_.add(input.readMessage(Diadoc.Api.Proto.DocumentIdOuterClass.DocumentId.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          documentIds_ = java.util.Collections.unmodifiableList(documentIds_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Diadoc.Api.Proto.CustomPrintFormDetection.internal_static_Diadoc_Api_Proto_CustomPrintFormDetectionRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Diadoc.Api.Proto.CustomPrintFormDetection.internal_static_Diadoc_Api_Proto_CustomPrintFormDetectionRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Diadoc.Api.Proto.CustomPrintFormDetection.CustomPrintFormDetectionRequest.class, Diadoc.Api.Proto.CustomPrintFormDetection.CustomPrintFormDetectionRequest.Builder.class);
    }

    public static com.google.protobuf.Parser<CustomPrintFormDetectionRequest> PARSER =
        new com.google.protobuf.AbstractParser<CustomPrintFormDetectionRequest>() {
      public CustomPrintFormDetectionRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CustomPrintFormDetectionRequest(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<CustomPrintFormDetectionRequest> getParserForType() {
      return PARSER;
    }

    public static final int DOCUMENTIDS_FIELD_NUMBER = 1;
    private java.util.List<Diadoc.Api.Proto.DocumentIdOuterClass.DocumentId> documentIds_;
    /**
     * <code>repeated .Diadoc.Api.Proto.DocumentId DocumentIds = 1;</code>
     */
    public java.util.List<Diadoc.Api.Proto.DocumentIdOuterClass.DocumentId> getDocumentIdsList() {
      return documentIds_;
    }
    /**
     * <code>repeated .Diadoc.Api.Proto.DocumentId DocumentIds = 1;</code>
     */
    public java.util.List<? extends Diadoc.Api.Proto.DocumentIdOuterClass.DocumentIdOrBuilder> 
        getDocumentIdsOrBuilderList() {
      return documentIds_;
    }
    /**
     * <code>repeated .Diadoc.Api.Proto.DocumentId DocumentIds = 1;</code>
     */
    public int getDocumentIdsCount() {
      return documentIds_.size();
    }
    /**
     * <code>repeated .Diadoc.Api.Proto.DocumentId DocumentIds = 1;</code>
     */
    public Diadoc.Api.Proto.DocumentIdOuterClass.DocumentId getDocumentIds(int index) {
      return documentIds_.get(index);
    }
    /**
     * <code>repeated .Diadoc.Api.Proto.DocumentId DocumentIds = 1;</code>
     */
    public Diadoc.Api.Proto.DocumentIdOuterClass.DocumentIdOrBuilder getDocumentIdsOrBuilder(
        int index) {
      return documentIds_.get(index);
    }

    private void initFields() {
      documentIds_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getDocumentIdsCount(); i++) {
        if (!getDocumentIds(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < documentIds_.size(); i++) {
        output.writeMessage(1, documentIds_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < documentIds_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, documentIds_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static Diadoc.Api.Proto.CustomPrintFormDetection.CustomPrintFormDetectionRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Diadoc.Api.Proto.CustomPrintFormDetection.CustomPrintFormDetectionRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Diadoc.Api.Proto.CustomPrintFormDetection.CustomPrintFormDetectionRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Diadoc.Api.Proto.CustomPrintFormDetection.CustomPrintFormDetectionRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Diadoc.Api.Proto.CustomPrintFormDetection.CustomPrintFormDetectionRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Diadoc.Api.Proto.CustomPrintFormDetection.CustomPrintFormDetectionRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static Diadoc.Api.Proto.CustomPrintFormDetection.CustomPrintFormDetectionRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static Diadoc.Api.Proto.CustomPrintFormDetection.CustomPrintFormDetectionRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static Diadoc.Api.Proto.CustomPrintFormDetection.CustomPrintFormDetectionRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Diadoc.Api.Proto.CustomPrintFormDetection.CustomPrintFormDetectionRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Diadoc.Api.Proto.CustomPrintFormDetection.CustomPrintFormDetectionRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Diadoc.Api.Proto.CustomPrintFormDetectionRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Diadoc.Api.Proto.CustomPrintFormDetectionRequest)
        Diadoc.Api.Proto.CustomPrintFormDetection.CustomPrintFormDetectionRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Diadoc.Api.Proto.CustomPrintFormDetection.internal_static_Diadoc_Api_Proto_CustomPrintFormDetectionRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Diadoc.Api.Proto.CustomPrintFormDetection.internal_static_Diadoc_Api_Proto_CustomPrintFormDetectionRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Diadoc.Api.Proto.CustomPrintFormDetection.CustomPrintFormDetectionRequest.class, Diadoc.Api.Proto.CustomPrintFormDetection.CustomPrintFormDetectionRequest.Builder.class);
      }

      // Construct using Diadoc.Api.Proto.CustomPrintFormDetection.CustomPrintFormDetectionRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getDocumentIdsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (documentIdsBuilder_ == null) {
          documentIds_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          documentIdsBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Diadoc.Api.Proto.CustomPrintFormDetection.internal_static_Diadoc_Api_Proto_CustomPrintFormDetectionRequest_descriptor;
      }

      public Diadoc.Api.Proto.CustomPrintFormDetection.CustomPrintFormDetectionRequest getDefaultInstanceForType() {
        return Diadoc.Api.Proto.CustomPrintFormDetection.CustomPrintFormDetectionRequest.getDefaultInstance();
      }

      public Diadoc.Api.Proto.CustomPrintFormDetection.CustomPrintFormDetectionRequest build() {
        Diadoc.Api.Proto.CustomPrintFormDetection.CustomPrintFormDetectionRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Diadoc.Api.Proto.CustomPrintFormDetection.CustomPrintFormDetectionRequest buildPartial() {
        Diadoc.Api.Proto.CustomPrintFormDetection.CustomPrintFormDetectionRequest result = new Diadoc.Api.Proto.CustomPrintFormDetection.CustomPrintFormDetectionRequest(this);
        int from_bitField0_ = bitField0_;
        if (documentIdsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            documentIds_ = java.util.Collections.unmodifiableList(documentIds_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.documentIds_ = documentIds_;
        } else {
          result.documentIds_ = documentIdsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Diadoc.Api.Proto.CustomPrintFormDetection.CustomPrintFormDetectionRequest) {
          return mergeFrom((Diadoc.Api.Proto.CustomPrintFormDetection.CustomPrintFormDetectionRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Diadoc.Api.Proto.CustomPrintFormDetection.CustomPrintFormDetectionRequest other) {
        if (other == Diadoc.Api.Proto.CustomPrintFormDetection.CustomPrintFormDetectionRequest.getDefaultInstance()) return this;
        if (documentIdsBuilder_ == null) {
          if (!other.documentIds_.isEmpty()) {
            if (documentIds_.isEmpty()) {
              documentIds_ = other.documentIds_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureDocumentIdsIsMutable();
              documentIds_.addAll(other.documentIds_);
            }
            onChanged();
          }
        } else {
          if (!other.documentIds_.isEmpty()) {
            if (documentIdsBuilder_.isEmpty()) {
              documentIdsBuilder_.dispose();
              documentIdsBuilder_ = null;
              documentIds_ = other.documentIds_;
              bitField0_ = (bitField0_ & ~0x00000001);
              documentIdsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getDocumentIdsFieldBuilder() : null;
            } else {
              documentIdsBuilder_.addAllMessages(other.documentIds_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getDocumentIdsCount(); i++) {
          if (!getDocumentIds(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Diadoc.Api.Proto.CustomPrintFormDetection.CustomPrintFormDetectionRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Diadoc.Api.Proto.CustomPrintFormDetection.CustomPrintFormDetectionRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<Diadoc.Api.Proto.DocumentIdOuterClass.DocumentId> documentIds_ =
        java.util.Collections.emptyList();
      private void ensureDocumentIdsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          documentIds_ = new java.util.ArrayList<Diadoc.Api.Proto.DocumentIdOuterClass.DocumentId>(documentIds_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          Diadoc.Api.Proto.DocumentIdOuterClass.DocumentId, Diadoc.Api.Proto.DocumentIdOuterClass.DocumentId.Builder, Diadoc.Api.Proto.DocumentIdOuterClass.DocumentIdOrBuilder> documentIdsBuilder_;

      /**
       * <code>repeated .Diadoc.Api.Proto.DocumentId DocumentIds = 1;</code>
       */
      public java.util.List<Diadoc.Api.Proto.DocumentIdOuterClass.DocumentId> getDocumentIdsList() {
        if (documentIdsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(documentIds_);
        } else {
          return documentIdsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Diadoc.Api.Proto.DocumentId DocumentIds = 1;</code>
       */
      public int getDocumentIdsCount() {
        if (documentIdsBuilder_ == null) {
          return documentIds_.size();
        } else {
          return documentIdsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Diadoc.Api.Proto.DocumentId DocumentIds = 1;</code>
       */
      public Diadoc.Api.Proto.DocumentIdOuterClass.DocumentId getDocumentIds(int index) {
        if (documentIdsBuilder_ == null) {
          return documentIds_.get(index);
        } else {
          return documentIdsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Diadoc.Api.Proto.DocumentId DocumentIds = 1;</code>
       */
      public Builder setDocumentIds(
          int index, Diadoc.Api.Proto.DocumentIdOuterClass.DocumentId value) {
        if (documentIdsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDocumentIdsIsMutable();
          documentIds_.set(index, value);
          onChanged();
        } else {
          documentIdsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Diadoc.Api.Proto.DocumentId DocumentIds = 1;</code>
       */
      public Builder setDocumentIds(
          int index, Diadoc.Api.Proto.DocumentIdOuterClass.DocumentId.Builder builderForValue) {
        if (documentIdsBuilder_ == null) {
          ensureDocumentIdsIsMutable();
          documentIds_.set(index, builderForValue.build());
          onChanged();
        } else {
          documentIdsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Diadoc.Api.Proto.DocumentId DocumentIds = 1;</code>
       */
      public Builder addDocumentIds(Diadoc.Api.Proto.DocumentIdOuterClass.DocumentId value) {
        if (documentIdsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDocumentIdsIsMutable();
          documentIds_.add(value);
          onChanged();
        } else {
          documentIdsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Diadoc.Api.Proto.DocumentId DocumentIds = 1;</code>
       */
      public Builder addDocumentIds(
          int index, Diadoc.Api.Proto.DocumentIdOuterClass.DocumentId value) {
        if (documentIdsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDocumentIdsIsMutable();
          documentIds_.add(index, value);
          onChanged();
        } else {
          documentIdsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Diadoc.Api.Proto.DocumentId DocumentIds = 1;</code>
       */
      public Builder addDocumentIds(
          Diadoc.Api.Proto.DocumentIdOuterClass.DocumentId.Builder builderForValue) {
        if (documentIdsBuilder_ == null) {
          ensureDocumentIdsIsMutable();
          documentIds_.add(builderForValue.build());
          onChanged();
        } else {
          documentIdsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Diadoc.Api.Proto.DocumentId DocumentIds = 1;</code>
       */
      public Builder addDocumentIds(
          int index, Diadoc.Api.Proto.DocumentIdOuterClass.DocumentId.Builder builderForValue) {
        if (documentIdsBuilder_ == null) {
          ensureDocumentIdsIsMutable();
          documentIds_.add(index, builderForValue.build());
          onChanged();
        } else {
          documentIdsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Diadoc.Api.Proto.DocumentId DocumentIds = 1;</code>
       */
      public Builder addAllDocumentIds(
          java.lang.Iterable<? extends Diadoc.Api.Proto.DocumentIdOuterClass.DocumentId> values) {
        if (documentIdsBuilder_ == null) {
          ensureDocumentIdsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, documentIds_);
          onChanged();
        } else {
          documentIdsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Diadoc.Api.Proto.DocumentId DocumentIds = 1;</code>
       */
      public Builder clearDocumentIds() {
        if (documentIdsBuilder_ == null) {
          documentIds_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          documentIdsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Diadoc.Api.Proto.DocumentId DocumentIds = 1;</code>
       */
      public Builder removeDocumentIds(int index) {
        if (documentIdsBuilder_ == null) {
          ensureDocumentIdsIsMutable();
          documentIds_.remove(index);
          onChanged();
        } else {
          documentIdsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Diadoc.Api.Proto.DocumentId DocumentIds = 1;</code>
       */
      public Diadoc.Api.Proto.DocumentIdOuterClass.DocumentId.Builder getDocumentIdsBuilder(
          int index) {
        return getDocumentIdsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Diadoc.Api.Proto.DocumentId DocumentIds = 1;</code>
       */
      public Diadoc.Api.Proto.DocumentIdOuterClass.DocumentIdOrBuilder getDocumentIdsOrBuilder(
          int index) {
        if (documentIdsBuilder_ == null) {
          return documentIds_.get(index);  } else {
          return documentIdsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Diadoc.Api.Proto.DocumentId DocumentIds = 1;</code>
       */
      public java.util.List<? extends Diadoc.Api.Proto.DocumentIdOuterClass.DocumentIdOrBuilder> 
           getDocumentIdsOrBuilderList() {
        if (documentIdsBuilder_ != null) {
          return documentIdsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(documentIds_);
        }
      }
      /**
       * <code>repeated .Diadoc.Api.Proto.DocumentId DocumentIds = 1;</code>
       */
      public Diadoc.Api.Proto.DocumentIdOuterClass.DocumentId.Builder addDocumentIdsBuilder() {
        return getDocumentIdsFieldBuilder().addBuilder(
            Diadoc.Api.Proto.DocumentIdOuterClass.DocumentId.getDefaultInstance());
      }
      /**
       * <code>repeated .Diadoc.Api.Proto.DocumentId DocumentIds = 1;</code>
       */
      public Diadoc.Api.Proto.DocumentIdOuterClass.DocumentId.Builder addDocumentIdsBuilder(
          int index) {
        return getDocumentIdsFieldBuilder().addBuilder(
            index, Diadoc.Api.Proto.DocumentIdOuterClass.DocumentId.getDefaultInstance());
      }
      /**
       * <code>repeated .Diadoc.Api.Proto.DocumentId DocumentIds = 1;</code>
       */
      public java.util.List<Diadoc.Api.Proto.DocumentIdOuterClass.DocumentId.Builder> 
           getDocumentIdsBuilderList() {
        return getDocumentIdsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          Diadoc.Api.Proto.DocumentIdOuterClass.DocumentId, Diadoc.Api.Proto.DocumentIdOuterClass.DocumentId.Builder, Diadoc.Api.Proto.DocumentIdOuterClass.DocumentIdOrBuilder> 
          getDocumentIdsFieldBuilder() {
        if (documentIdsBuilder_ == null) {
          documentIdsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              Diadoc.Api.Proto.DocumentIdOuterClass.DocumentId, Diadoc.Api.Proto.DocumentIdOuterClass.DocumentId.Builder, Diadoc.Api.Proto.DocumentIdOuterClass.DocumentIdOrBuilder>(
                  documentIds_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          documentIds_ = null;
        }
        return documentIdsBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:Diadoc.Api.Proto.CustomPrintFormDetectionRequest)
    }

    static {
      defaultInstance = new CustomPrintFormDetectionRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Diadoc.Api.Proto.CustomPrintFormDetectionRequest)
  }

  public interface CustomPrintFormDetectionResultOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Diadoc.Api.Proto.CustomPrintFormDetectionResult)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .Diadoc.Api.Proto.CustomPrintFormDetectionItemResult Items = 1;</code>
     */
    java.util.List<Diadoc.Api.Proto.CustomPrintFormDetection.CustomPrintFormDetectionItemResult> 
        getItemsList();
    /**
     * <code>repeated .Diadoc.Api.Proto.CustomPrintFormDetectionItemResult Items = 1;</code>
     */
    Diadoc.Api.Proto.CustomPrintFormDetection.CustomPrintFormDetectionItemResult getItems(int index);
    /**
     * <code>repeated .Diadoc.Api.Proto.CustomPrintFormDetectionItemResult Items = 1;</code>
     */
    int getItemsCount();
    /**
     * <code>repeated .Diadoc.Api.Proto.CustomPrintFormDetectionItemResult Items = 1;</code>
     */
    java.util.List<? extends Diadoc.Api.Proto.CustomPrintFormDetection.CustomPrintFormDetectionItemResultOrBuilder> 
        getItemsOrBuilderList();
    /**
     * <code>repeated .Diadoc.Api.Proto.CustomPrintFormDetectionItemResult Items = 1;</code>
     */
    Diadoc.Api.Proto.CustomPrintFormDetection.CustomPrintFormDetectionItemResultOrBuilder getItemsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code Diadoc.Api.Proto.CustomPrintFormDetectionResult}
   */
  public static final class CustomPrintFormDetectionResult extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Diadoc.Api.Proto.CustomPrintFormDetectionResult)
      CustomPrintFormDetectionResultOrBuilder {
    // Use CustomPrintFormDetectionResult.newBuilder() to construct.
    private CustomPrintFormDetectionResult(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private CustomPrintFormDetectionResult(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final CustomPrintFormDetectionResult defaultInstance;
    public static CustomPrintFormDetectionResult getDefaultInstance() {
      return defaultInstance;
    }

    public CustomPrintFormDetectionResult getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private CustomPrintFormDetectionResult(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                items_ = new java.util.ArrayList<Diadoc.Api.Proto.CustomPrintFormDetection.CustomPrintFormDetectionItemResult>();
                mutable_bitField0_ |= 0x00000001;
              }
              items_.add(input.readMessage(Diadoc.Api.Proto.CustomPrintFormDetection.CustomPrintFormDetectionItemResult.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          items_ = java.util.Collections.unmodifiableList(items_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Diadoc.Api.Proto.CustomPrintFormDetection.internal_static_Diadoc_Api_Proto_CustomPrintFormDetectionResult_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Diadoc.Api.Proto.CustomPrintFormDetection.internal_static_Diadoc_Api_Proto_CustomPrintFormDetectionResult_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Diadoc.Api.Proto.CustomPrintFormDetection.CustomPrintFormDetectionResult.class, Diadoc.Api.Proto.CustomPrintFormDetection.CustomPrintFormDetectionResult.Builder.class);
    }

    public static com.google.protobuf.Parser<CustomPrintFormDetectionResult> PARSER =
        new com.google.protobuf.AbstractParser<CustomPrintFormDetectionResult>() {
      public CustomPrintFormDetectionResult parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CustomPrintFormDetectionResult(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<CustomPrintFormDetectionResult> getParserForType() {
      return PARSER;
    }

    public static final int ITEMS_FIELD_NUMBER = 1;
    private java.util.List<Diadoc.Api.Proto.CustomPrintFormDetection.CustomPrintFormDetectionItemResult> items_;
    /**
     * <code>repeated .Diadoc.Api.Proto.CustomPrintFormDetectionItemResult Items = 1;</code>
     */
    public java.util.List<Diadoc.Api.Proto.CustomPrintFormDetection.CustomPrintFormDetectionItemResult> getItemsList() {
      return items_;
    }
    /**
     * <code>repeated .Diadoc.Api.Proto.CustomPrintFormDetectionItemResult Items = 1;</code>
     */
    public java.util.List<? extends Diadoc.Api.Proto.CustomPrintFormDetection.CustomPrintFormDetectionItemResultOrBuilder> 
        getItemsOrBuilderList() {
      return items_;
    }
    /**
     * <code>repeated .Diadoc.Api.Proto.CustomPrintFormDetectionItemResult Items = 1;</code>
     */
    public int getItemsCount() {
      return items_.size();
    }
    /**
     * <code>repeated .Diadoc.Api.Proto.CustomPrintFormDetectionItemResult Items = 1;</code>
     */
    public Diadoc.Api.Proto.CustomPrintFormDetection.CustomPrintFormDetectionItemResult getItems(int index) {
      return items_.get(index);
    }
    /**
     * <code>repeated .Diadoc.Api.Proto.CustomPrintFormDetectionItemResult Items = 1;</code>
     */
    public Diadoc.Api.Proto.CustomPrintFormDetection.CustomPrintFormDetectionItemResultOrBuilder getItemsOrBuilder(
        int index) {
      return items_.get(index);
    }

    private void initFields() {
      items_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getItemsCount(); i++) {
        if (!getItems(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < items_.size(); i++) {
        output.writeMessage(1, items_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < items_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, items_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static Diadoc.Api.Proto.CustomPrintFormDetection.CustomPrintFormDetectionResult parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Diadoc.Api.Proto.CustomPrintFormDetection.CustomPrintFormDetectionResult parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Diadoc.Api.Proto.CustomPrintFormDetection.CustomPrintFormDetectionResult parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Diadoc.Api.Proto.CustomPrintFormDetection.CustomPrintFormDetectionResult parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Diadoc.Api.Proto.CustomPrintFormDetection.CustomPrintFormDetectionResult parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Diadoc.Api.Proto.CustomPrintFormDetection.CustomPrintFormDetectionResult parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static Diadoc.Api.Proto.CustomPrintFormDetection.CustomPrintFormDetectionResult parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static Diadoc.Api.Proto.CustomPrintFormDetection.CustomPrintFormDetectionResult parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static Diadoc.Api.Proto.CustomPrintFormDetection.CustomPrintFormDetectionResult parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Diadoc.Api.Proto.CustomPrintFormDetection.CustomPrintFormDetectionResult parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Diadoc.Api.Proto.CustomPrintFormDetection.CustomPrintFormDetectionResult prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Diadoc.Api.Proto.CustomPrintFormDetectionResult}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Diadoc.Api.Proto.CustomPrintFormDetectionResult)
        Diadoc.Api.Proto.CustomPrintFormDetection.CustomPrintFormDetectionResultOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Diadoc.Api.Proto.CustomPrintFormDetection.internal_static_Diadoc_Api_Proto_CustomPrintFormDetectionResult_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Diadoc.Api.Proto.CustomPrintFormDetection.internal_static_Diadoc_Api_Proto_CustomPrintFormDetectionResult_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Diadoc.Api.Proto.CustomPrintFormDetection.CustomPrintFormDetectionResult.class, Diadoc.Api.Proto.CustomPrintFormDetection.CustomPrintFormDetectionResult.Builder.class);
      }

      // Construct using Diadoc.Api.Proto.CustomPrintFormDetection.CustomPrintFormDetectionResult.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getItemsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (itemsBuilder_ == null) {
          items_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          itemsBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Diadoc.Api.Proto.CustomPrintFormDetection.internal_static_Diadoc_Api_Proto_CustomPrintFormDetectionResult_descriptor;
      }

      public Diadoc.Api.Proto.CustomPrintFormDetection.CustomPrintFormDetectionResult getDefaultInstanceForType() {
        return Diadoc.Api.Proto.CustomPrintFormDetection.CustomPrintFormDetectionResult.getDefaultInstance();
      }

      public Diadoc.Api.Proto.CustomPrintFormDetection.CustomPrintFormDetectionResult build() {
        Diadoc.Api.Proto.CustomPrintFormDetection.CustomPrintFormDetectionResult result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Diadoc.Api.Proto.CustomPrintFormDetection.CustomPrintFormDetectionResult buildPartial() {
        Diadoc.Api.Proto.CustomPrintFormDetection.CustomPrintFormDetectionResult result = new Diadoc.Api.Proto.CustomPrintFormDetection.CustomPrintFormDetectionResult(this);
        int from_bitField0_ = bitField0_;
        if (itemsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            items_ = java.util.Collections.unmodifiableList(items_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.items_ = items_;
        } else {
          result.items_ = itemsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Diadoc.Api.Proto.CustomPrintFormDetection.CustomPrintFormDetectionResult) {
          return mergeFrom((Diadoc.Api.Proto.CustomPrintFormDetection.CustomPrintFormDetectionResult)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Diadoc.Api.Proto.CustomPrintFormDetection.CustomPrintFormDetectionResult other) {
        if (other == Diadoc.Api.Proto.CustomPrintFormDetection.CustomPrintFormDetectionResult.getDefaultInstance()) return this;
        if (itemsBuilder_ == null) {
          if (!other.items_.isEmpty()) {
            if (items_.isEmpty()) {
              items_ = other.items_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureItemsIsMutable();
              items_.addAll(other.items_);
            }
            onChanged();
          }
        } else {
          if (!other.items_.isEmpty()) {
            if (itemsBuilder_.isEmpty()) {
              itemsBuilder_.dispose();
              itemsBuilder_ = null;
              items_ = other.items_;
              bitField0_ = (bitField0_ & ~0x00000001);
              itemsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getItemsFieldBuilder() : null;
            } else {
              itemsBuilder_.addAllMessages(other.items_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getItemsCount(); i++) {
          if (!getItems(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Diadoc.Api.Proto.CustomPrintFormDetection.CustomPrintFormDetectionResult parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Diadoc.Api.Proto.CustomPrintFormDetection.CustomPrintFormDetectionResult) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<Diadoc.Api.Proto.CustomPrintFormDetection.CustomPrintFormDetectionItemResult> items_ =
        java.util.Collections.emptyList();
      private void ensureItemsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          items_ = new java.util.ArrayList<Diadoc.Api.Proto.CustomPrintFormDetection.CustomPrintFormDetectionItemResult>(items_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          Diadoc.Api.Proto.CustomPrintFormDetection.CustomPrintFormDetectionItemResult, Diadoc.Api.Proto.CustomPrintFormDetection.CustomPrintFormDetectionItemResult.Builder, Diadoc.Api.Proto.CustomPrintFormDetection.CustomPrintFormDetectionItemResultOrBuilder> itemsBuilder_;

      /**
       * <code>repeated .Diadoc.Api.Proto.CustomPrintFormDetectionItemResult Items = 1;</code>
       */
      public java.util.List<Diadoc.Api.Proto.CustomPrintFormDetection.CustomPrintFormDetectionItemResult> getItemsList() {
        if (itemsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(items_);
        } else {
          return itemsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Diadoc.Api.Proto.CustomPrintFormDetectionItemResult Items = 1;</code>
       */
      public int getItemsCount() {
        if (itemsBuilder_ == null) {
          return items_.size();
        } else {
          return itemsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Diadoc.Api.Proto.CustomPrintFormDetectionItemResult Items = 1;</code>
       */
      public Diadoc.Api.Proto.CustomPrintFormDetection.CustomPrintFormDetectionItemResult getItems(int index) {
        if (itemsBuilder_ == null) {
          return items_.get(index);
        } else {
          return itemsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Diadoc.Api.Proto.CustomPrintFormDetectionItemResult Items = 1;</code>
       */
      public Builder setItems(
          int index, Diadoc.Api.Proto.CustomPrintFormDetection.CustomPrintFormDetectionItemResult value) {
        if (itemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemsIsMutable();
          items_.set(index, value);
          onChanged();
        } else {
          itemsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Diadoc.Api.Proto.CustomPrintFormDetectionItemResult Items = 1;</code>
       */
      public Builder setItems(
          int index, Diadoc.Api.Proto.CustomPrintFormDetection.CustomPrintFormDetectionItemResult.Builder builderForValue) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.set(index, builderForValue.build());
          onChanged();
        } else {
          itemsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Diadoc.Api.Proto.CustomPrintFormDetectionItemResult Items = 1;</code>
       */
      public Builder addItems(Diadoc.Api.Proto.CustomPrintFormDetection.CustomPrintFormDetectionItemResult value) {
        if (itemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemsIsMutable();
          items_.add(value);
          onChanged();
        } else {
          itemsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Diadoc.Api.Proto.CustomPrintFormDetectionItemResult Items = 1;</code>
       */
      public Builder addItems(
          int index, Diadoc.Api.Proto.CustomPrintFormDetection.CustomPrintFormDetectionItemResult value) {
        if (itemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemsIsMutable();
          items_.add(index, value);
          onChanged();
        } else {
          itemsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Diadoc.Api.Proto.CustomPrintFormDetectionItemResult Items = 1;</code>
       */
      public Builder addItems(
          Diadoc.Api.Proto.CustomPrintFormDetection.CustomPrintFormDetectionItemResult.Builder builderForValue) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.add(builderForValue.build());
          onChanged();
        } else {
          itemsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Diadoc.Api.Proto.CustomPrintFormDetectionItemResult Items = 1;</code>
       */
      public Builder addItems(
          int index, Diadoc.Api.Proto.CustomPrintFormDetection.CustomPrintFormDetectionItemResult.Builder builderForValue) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.add(index, builderForValue.build());
          onChanged();
        } else {
          itemsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Diadoc.Api.Proto.CustomPrintFormDetectionItemResult Items = 1;</code>
       */
      public Builder addAllItems(
          java.lang.Iterable<? extends Diadoc.Api.Proto.CustomPrintFormDetection.CustomPrintFormDetectionItemResult> values) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, items_);
          onChanged();
        } else {
          itemsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Diadoc.Api.Proto.CustomPrintFormDetectionItemResult Items = 1;</code>
       */
      public Builder clearItems() {
        if (itemsBuilder_ == null) {
          items_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          itemsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Diadoc.Api.Proto.CustomPrintFormDetectionItemResult Items = 1;</code>
       */
      public Builder removeItems(int index) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.remove(index);
          onChanged();
        } else {
          itemsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Diadoc.Api.Proto.CustomPrintFormDetectionItemResult Items = 1;</code>
       */
      public Diadoc.Api.Proto.CustomPrintFormDetection.CustomPrintFormDetectionItemResult.Builder getItemsBuilder(
          int index) {
        return getItemsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Diadoc.Api.Proto.CustomPrintFormDetectionItemResult Items = 1;</code>
       */
      public Diadoc.Api.Proto.CustomPrintFormDetection.CustomPrintFormDetectionItemResultOrBuilder getItemsOrBuilder(
          int index) {
        if (itemsBuilder_ == null) {
          return items_.get(index);  } else {
          return itemsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Diadoc.Api.Proto.CustomPrintFormDetectionItemResult Items = 1;</code>
       */
      public java.util.List<? extends Diadoc.Api.Proto.CustomPrintFormDetection.CustomPrintFormDetectionItemResultOrBuilder> 
           getItemsOrBuilderList() {
        if (itemsBuilder_ != null) {
          return itemsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(items_);
        }
      }
      /**
       * <code>repeated .Diadoc.Api.Proto.CustomPrintFormDetectionItemResult Items = 1;</code>
       */
      public Diadoc.Api.Proto.CustomPrintFormDetection.CustomPrintFormDetectionItemResult.Builder addItemsBuilder() {
        return getItemsFieldBuilder().addBuilder(
            Diadoc.Api.Proto.CustomPrintFormDetection.CustomPrintFormDetectionItemResult.getDefaultInstance());
      }
      /**
       * <code>repeated .Diadoc.Api.Proto.CustomPrintFormDetectionItemResult Items = 1;</code>
       */
      public Diadoc.Api.Proto.CustomPrintFormDetection.CustomPrintFormDetectionItemResult.Builder addItemsBuilder(
          int index) {
        return getItemsFieldBuilder().addBuilder(
            index, Diadoc.Api.Proto.CustomPrintFormDetection.CustomPrintFormDetectionItemResult.getDefaultInstance());
      }
      /**
       * <code>repeated .Diadoc.Api.Proto.CustomPrintFormDetectionItemResult Items = 1;</code>
       */
      public java.util.List<Diadoc.Api.Proto.CustomPrintFormDetection.CustomPrintFormDetectionItemResult.Builder> 
           getItemsBuilderList() {
        return getItemsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          Diadoc.Api.Proto.CustomPrintFormDetection.CustomPrintFormDetectionItemResult, Diadoc.Api.Proto.CustomPrintFormDetection.CustomPrintFormDetectionItemResult.Builder, Diadoc.Api.Proto.CustomPrintFormDetection.CustomPrintFormDetectionItemResultOrBuilder> 
          getItemsFieldBuilder() {
        if (itemsBuilder_ == null) {
          itemsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              Diadoc.Api.Proto.CustomPrintFormDetection.CustomPrintFormDetectionItemResult, Diadoc.Api.Proto.CustomPrintFormDetection.CustomPrintFormDetectionItemResult.Builder, Diadoc.Api.Proto.CustomPrintFormDetection.CustomPrintFormDetectionItemResultOrBuilder>(
                  items_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          items_ = null;
        }
        return itemsBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:Diadoc.Api.Proto.CustomPrintFormDetectionResult)
    }

    static {
      defaultInstance = new CustomPrintFormDetectionResult(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Diadoc.Api.Proto.CustomPrintFormDetectionResult)
  }

  public interface CustomPrintFormDetectionItemResultOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Diadoc.Api.Proto.CustomPrintFormDetectionItemResult)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .Diadoc.Api.Proto.DocumentId DocumentId = 1;</code>
     */
    boolean hasDocumentId();
    /**
     * <code>required .Diadoc.Api.Proto.DocumentId DocumentId = 1;</code>
     */
    Diadoc.Api.Proto.DocumentIdOuterClass.DocumentId getDocumentId();
    /**
     * <code>required .Diadoc.Api.Proto.DocumentId DocumentId = 1;</code>
     */
    Diadoc.Api.Proto.DocumentIdOuterClass.DocumentIdOrBuilder getDocumentIdOrBuilder();

    /**
     * <code>required bool HasCustomPrintForm = 2;</code>
     */
    boolean hasHasCustomPrintForm();
    /**
     * <code>required bool HasCustomPrintForm = 2;</code>
     */
    boolean getHasCustomPrintForm();
  }
  /**
   * Protobuf type {@code Diadoc.Api.Proto.CustomPrintFormDetectionItemResult}
   */
  public static final class CustomPrintFormDetectionItemResult extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Diadoc.Api.Proto.CustomPrintFormDetectionItemResult)
      CustomPrintFormDetectionItemResultOrBuilder {
    // Use CustomPrintFormDetectionItemResult.newBuilder() to construct.
    private CustomPrintFormDetectionItemResult(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private CustomPrintFormDetectionItemResult(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final CustomPrintFormDetectionItemResult defaultInstance;
    public static CustomPrintFormDetectionItemResult getDefaultInstance() {
      return defaultInstance;
    }

    public CustomPrintFormDetectionItemResult getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private CustomPrintFormDetectionItemResult(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              Diadoc.Api.Proto.DocumentIdOuterClass.DocumentId.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = documentId_.toBuilder();
              }
              documentId_ = input.readMessage(Diadoc.Api.Proto.DocumentIdOuterClass.DocumentId.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(documentId_);
                documentId_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              hasCustomPrintForm_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Diadoc.Api.Proto.CustomPrintFormDetection.internal_static_Diadoc_Api_Proto_CustomPrintFormDetectionItemResult_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Diadoc.Api.Proto.CustomPrintFormDetection.internal_static_Diadoc_Api_Proto_CustomPrintFormDetectionItemResult_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Diadoc.Api.Proto.CustomPrintFormDetection.CustomPrintFormDetectionItemResult.class, Diadoc.Api.Proto.CustomPrintFormDetection.CustomPrintFormDetectionItemResult.Builder.class);
    }

    public static com.google.protobuf.Parser<CustomPrintFormDetectionItemResult> PARSER =
        new com.google.protobuf.AbstractParser<CustomPrintFormDetectionItemResult>() {
      public CustomPrintFormDetectionItemResult parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CustomPrintFormDetectionItemResult(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<CustomPrintFormDetectionItemResult> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int DOCUMENTID_FIELD_NUMBER = 1;
    private Diadoc.Api.Proto.DocumentIdOuterClass.DocumentId documentId_;
    /**
     * <code>required .Diadoc.Api.Proto.DocumentId DocumentId = 1;</code>
     */
    public boolean hasDocumentId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .Diadoc.Api.Proto.DocumentId DocumentId = 1;</code>
     */
    public Diadoc.Api.Proto.DocumentIdOuterClass.DocumentId getDocumentId() {
      return documentId_;
    }
    /**
     * <code>required .Diadoc.Api.Proto.DocumentId DocumentId = 1;</code>
     */
    public Diadoc.Api.Proto.DocumentIdOuterClass.DocumentIdOrBuilder getDocumentIdOrBuilder() {
      return documentId_;
    }

    public static final int HASCUSTOMPRINTFORM_FIELD_NUMBER = 2;
    private boolean hasCustomPrintForm_;
    /**
     * <code>required bool HasCustomPrintForm = 2;</code>
     */
    public boolean hasHasCustomPrintForm() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required bool HasCustomPrintForm = 2;</code>
     */
    public boolean getHasCustomPrintForm() {
      return hasCustomPrintForm_;
    }

    private void initFields() {
      documentId_ = Diadoc.Api.Proto.DocumentIdOuterClass.DocumentId.getDefaultInstance();
      hasCustomPrintForm_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasDocumentId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasHasCustomPrintForm()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getDocumentId().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, documentId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBool(2, hasCustomPrintForm_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, documentId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, hasCustomPrintForm_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static Diadoc.Api.Proto.CustomPrintFormDetection.CustomPrintFormDetectionItemResult parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Diadoc.Api.Proto.CustomPrintFormDetection.CustomPrintFormDetectionItemResult parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Diadoc.Api.Proto.CustomPrintFormDetection.CustomPrintFormDetectionItemResult parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Diadoc.Api.Proto.CustomPrintFormDetection.CustomPrintFormDetectionItemResult parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Diadoc.Api.Proto.CustomPrintFormDetection.CustomPrintFormDetectionItemResult parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Diadoc.Api.Proto.CustomPrintFormDetection.CustomPrintFormDetectionItemResult parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static Diadoc.Api.Proto.CustomPrintFormDetection.CustomPrintFormDetectionItemResult parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static Diadoc.Api.Proto.CustomPrintFormDetection.CustomPrintFormDetectionItemResult parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static Diadoc.Api.Proto.CustomPrintFormDetection.CustomPrintFormDetectionItemResult parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Diadoc.Api.Proto.CustomPrintFormDetection.CustomPrintFormDetectionItemResult parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Diadoc.Api.Proto.CustomPrintFormDetection.CustomPrintFormDetectionItemResult prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Diadoc.Api.Proto.CustomPrintFormDetectionItemResult}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Diadoc.Api.Proto.CustomPrintFormDetectionItemResult)
        Diadoc.Api.Proto.CustomPrintFormDetection.CustomPrintFormDetectionItemResultOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Diadoc.Api.Proto.CustomPrintFormDetection.internal_static_Diadoc_Api_Proto_CustomPrintFormDetectionItemResult_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Diadoc.Api.Proto.CustomPrintFormDetection.internal_static_Diadoc_Api_Proto_CustomPrintFormDetectionItemResult_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Diadoc.Api.Proto.CustomPrintFormDetection.CustomPrintFormDetectionItemResult.class, Diadoc.Api.Proto.CustomPrintFormDetection.CustomPrintFormDetectionItemResult.Builder.class);
      }

      // Construct using Diadoc.Api.Proto.CustomPrintFormDetection.CustomPrintFormDetectionItemResult.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getDocumentIdFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (documentIdBuilder_ == null) {
          documentId_ = Diadoc.Api.Proto.DocumentIdOuterClass.DocumentId.getDefaultInstance();
        } else {
          documentIdBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        hasCustomPrintForm_ = false;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Diadoc.Api.Proto.CustomPrintFormDetection.internal_static_Diadoc_Api_Proto_CustomPrintFormDetectionItemResult_descriptor;
      }

      public Diadoc.Api.Proto.CustomPrintFormDetection.CustomPrintFormDetectionItemResult getDefaultInstanceForType() {
        return Diadoc.Api.Proto.CustomPrintFormDetection.CustomPrintFormDetectionItemResult.getDefaultInstance();
      }

      public Diadoc.Api.Proto.CustomPrintFormDetection.CustomPrintFormDetectionItemResult build() {
        Diadoc.Api.Proto.CustomPrintFormDetection.CustomPrintFormDetectionItemResult result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Diadoc.Api.Proto.CustomPrintFormDetection.CustomPrintFormDetectionItemResult buildPartial() {
        Diadoc.Api.Proto.CustomPrintFormDetection.CustomPrintFormDetectionItemResult result = new Diadoc.Api.Proto.CustomPrintFormDetection.CustomPrintFormDetectionItemResult(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (documentIdBuilder_ == null) {
          result.documentId_ = documentId_;
        } else {
          result.documentId_ = documentIdBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.hasCustomPrintForm_ = hasCustomPrintForm_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Diadoc.Api.Proto.CustomPrintFormDetection.CustomPrintFormDetectionItemResult) {
          return mergeFrom((Diadoc.Api.Proto.CustomPrintFormDetection.CustomPrintFormDetectionItemResult)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Diadoc.Api.Proto.CustomPrintFormDetection.CustomPrintFormDetectionItemResult other) {
        if (other == Diadoc.Api.Proto.CustomPrintFormDetection.CustomPrintFormDetectionItemResult.getDefaultInstance()) return this;
        if (other.hasDocumentId()) {
          mergeDocumentId(other.getDocumentId());
        }
        if (other.hasHasCustomPrintForm()) {
          setHasCustomPrintForm(other.getHasCustomPrintForm());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasDocumentId()) {
          
          return false;
        }
        if (!hasHasCustomPrintForm()) {
          
          return false;
        }
        if (!getDocumentId().isInitialized()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Diadoc.Api.Proto.CustomPrintFormDetection.CustomPrintFormDetectionItemResult parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Diadoc.Api.Proto.CustomPrintFormDetection.CustomPrintFormDetectionItemResult) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private Diadoc.Api.Proto.DocumentIdOuterClass.DocumentId documentId_ = Diadoc.Api.Proto.DocumentIdOuterClass.DocumentId.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          Diadoc.Api.Proto.DocumentIdOuterClass.DocumentId, Diadoc.Api.Proto.DocumentIdOuterClass.DocumentId.Builder, Diadoc.Api.Proto.DocumentIdOuterClass.DocumentIdOrBuilder> documentIdBuilder_;
      /**
       * <code>required .Diadoc.Api.Proto.DocumentId DocumentId = 1;</code>
       */
      public boolean hasDocumentId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .Diadoc.Api.Proto.DocumentId DocumentId = 1;</code>
       */
      public Diadoc.Api.Proto.DocumentIdOuterClass.DocumentId getDocumentId() {
        if (documentIdBuilder_ == null) {
          return documentId_;
        } else {
          return documentIdBuilder_.getMessage();
        }
      }
      /**
       * <code>required .Diadoc.Api.Proto.DocumentId DocumentId = 1;</code>
       */
      public Builder setDocumentId(Diadoc.Api.Proto.DocumentIdOuterClass.DocumentId value) {
        if (documentIdBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          documentId_ = value;
          onChanged();
        } else {
          documentIdBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .Diadoc.Api.Proto.DocumentId DocumentId = 1;</code>
       */
      public Builder setDocumentId(
          Diadoc.Api.Proto.DocumentIdOuterClass.DocumentId.Builder builderForValue) {
        if (documentIdBuilder_ == null) {
          documentId_ = builderForValue.build();
          onChanged();
        } else {
          documentIdBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .Diadoc.Api.Proto.DocumentId DocumentId = 1;</code>
       */
      public Builder mergeDocumentId(Diadoc.Api.Proto.DocumentIdOuterClass.DocumentId value) {
        if (documentIdBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              documentId_ != Diadoc.Api.Proto.DocumentIdOuterClass.DocumentId.getDefaultInstance()) {
            documentId_ =
              Diadoc.Api.Proto.DocumentIdOuterClass.DocumentId.newBuilder(documentId_).mergeFrom(value).buildPartial();
          } else {
            documentId_ = value;
          }
          onChanged();
        } else {
          documentIdBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .Diadoc.Api.Proto.DocumentId DocumentId = 1;</code>
       */
      public Builder clearDocumentId() {
        if (documentIdBuilder_ == null) {
          documentId_ = Diadoc.Api.Proto.DocumentIdOuterClass.DocumentId.getDefaultInstance();
          onChanged();
        } else {
          documentIdBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>required .Diadoc.Api.Proto.DocumentId DocumentId = 1;</code>
       */
      public Diadoc.Api.Proto.DocumentIdOuterClass.DocumentId.Builder getDocumentIdBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getDocumentIdFieldBuilder().getBuilder();
      }
      /**
       * <code>required .Diadoc.Api.Proto.DocumentId DocumentId = 1;</code>
       */
      public Diadoc.Api.Proto.DocumentIdOuterClass.DocumentIdOrBuilder getDocumentIdOrBuilder() {
        if (documentIdBuilder_ != null) {
          return documentIdBuilder_.getMessageOrBuilder();
        } else {
          return documentId_;
        }
      }
      /**
       * <code>required .Diadoc.Api.Proto.DocumentId DocumentId = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          Diadoc.Api.Proto.DocumentIdOuterClass.DocumentId, Diadoc.Api.Proto.DocumentIdOuterClass.DocumentId.Builder, Diadoc.Api.Proto.DocumentIdOuterClass.DocumentIdOrBuilder> 
          getDocumentIdFieldBuilder() {
        if (documentIdBuilder_ == null) {
          documentIdBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              Diadoc.Api.Proto.DocumentIdOuterClass.DocumentId, Diadoc.Api.Proto.DocumentIdOuterClass.DocumentId.Builder, Diadoc.Api.Proto.DocumentIdOuterClass.DocumentIdOrBuilder>(
                  getDocumentId(),
                  getParentForChildren(),
                  isClean());
          documentId_ = null;
        }
        return documentIdBuilder_;
      }

      private boolean hasCustomPrintForm_ ;
      /**
       * <code>required bool HasCustomPrintForm = 2;</code>
       */
      public boolean hasHasCustomPrintForm() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required bool HasCustomPrintForm = 2;</code>
       */
      public boolean getHasCustomPrintForm() {
        return hasCustomPrintForm_;
      }
      /**
       * <code>required bool HasCustomPrintForm = 2;</code>
       */
      public Builder setHasCustomPrintForm(boolean value) {
        bitField0_ |= 0x00000002;
        hasCustomPrintForm_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bool HasCustomPrintForm = 2;</code>
       */
      public Builder clearHasCustomPrintForm() {
        bitField0_ = (bitField0_ & ~0x00000002);
        hasCustomPrintForm_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Diadoc.Api.Proto.CustomPrintFormDetectionItemResult)
    }

    static {
      defaultInstance = new CustomPrintFormDetectionItemResult(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Diadoc.Api.Proto.CustomPrintFormDetectionItemResult)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Diadoc_Api_Proto_CustomPrintFormDetectionRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Diadoc_Api_Proto_CustomPrintFormDetectionRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Diadoc_Api_Proto_CustomPrintFormDetectionResult_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Diadoc_Api_Proto_CustomPrintFormDetectionResult_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Diadoc_Api_Proto_CustomPrintFormDetectionItemResult_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Diadoc_Api_Proto_CustomPrintFormDetectionItemResult_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\036CustomPrintFormDetection.proto\022\020Diadoc" +
      ".Api.Proto\032\020DocumentId.proto\"T\n\037CustomPr" +
      "intFormDetectionRequest\0221\n\013DocumentIds\030\001" +
      " \003(\0132\034.Diadoc.Api.Proto.DocumentId\"e\n\036Cu" +
      "stomPrintFormDetectionResult\022C\n\005Items\030\001 " +
      "\003(\01324.Diadoc.Api.Proto.CustomPrintFormDe" +
      "tectionItemResult\"r\n\"CustomPrintFormDete" +
      "ctionItemResult\0220\n\nDocumentId\030\001 \002(\0132\034.Di" +
      "adoc.Api.Proto.DocumentId\022\032\n\022HasCustomPr" +
      "intForm\030\002 \002(\010"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          Diadoc.Api.Proto.DocumentIdOuterClass.getDescriptor(),
        }, assigner);
    internal_static_Diadoc_Api_Proto_CustomPrintFormDetectionRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Diadoc_Api_Proto_CustomPrintFormDetectionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Diadoc_Api_Proto_CustomPrintFormDetectionRequest_descriptor,
        new java.lang.String[] { "DocumentIds", });
    internal_static_Diadoc_Api_Proto_CustomPrintFormDetectionResult_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Diadoc_Api_Proto_CustomPrintFormDetectionResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Diadoc_Api_Proto_CustomPrintFormDetectionResult_descriptor,
        new java.lang.String[] { "Items", });
    internal_static_Diadoc_Api_Proto_CustomPrintFormDetectionItemResult_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Diadoc_Api_Proto_CustomPrintFormDetectionItemResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Diadoc_Api_Proto_CustomPrintFormDetectionItemResult_descriptor,
        new java.lang.String[] { "DocumentId", "HasCustomPrintForm", });
    Diadoc.Api.Proto.DocumentIdOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
