// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CounteragentGroups/CounteragentGroupToUpdate.proto

package Diadoc.Api.Proto.CounteragentGroups;

public final class CounteragentGroupToUpdateOuterClass {
  private CounteragentGroupToUpdateOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface CounteragentGroupToUpdateOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Diadoc.Api.Proto.CounteragentGroups.CounteragentGroupToUpdate)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string Name = 1;</code>
     */
    boolean hasName();
    /**
     * <code>optional string Name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>optional string Name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>optional .Diadoc.Api.Proto.CounteragentGroups.CounteragentGroupDepartmentPatch GroupDepartments = 2;</code>
     */
    boolean hasGroupDepartments();
    /**
     * <code>optional .Diadoc.Api.Proto.CounteragentGroups.CounteragentGroupDepartmentPatch GroupDepartments = 2;</code>
     */
    Diadoc.Api.Proto.CounteragentGroups.CounteragentGroupToUpdateOuterClass.CounteragentGroupDepartmentPatch getGroupDepartments();
    /**
     * <code>optional .Diadoc.Api.Proto.CounteragentGroups.CounteragentGroupDepartmentPatch GroupDepartments = 2;</code>
     */
    Diadoc.Api.Proto.CounteragentGroups.CounteragentGroupToUpdateOuterClass.CounteragentGroupDepartmentPatchOrBuilder getGroupDepartmentsOrBuilder();
  }
  /**
   * Protobuf type {@code Diadoc.Api.Proto.CounteragentGroups.CounteragentGroupToUpdate}
   */
  public static final class CounteragentGroupToUpdate extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Diadoc.Api.Proto.CounteragentGroups.CounteragentGroupToUpdate)
      CounteragentGroupToUpdateOrBuilder {
    // Use CounteragentGroupToUpdate.newBuilder() to construct.
    private CounteragentGroupToUpdate(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private CounteragentGroupToUpdate(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final CounteragentGroupToUpdate defaultInstance;
    public static CounteragentGroupToUpdate getDefaultInstance() {
      return defaultInstance;
    }

    public CounteragentGroupToUpdate getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private CounteragentGroupToUpdate(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              name_ = bs;
              break;
            }
            case 18: {
              Diadoc.Api.Proto.CounteragentGroups.CounteragentGroupToUpdateOuterClass.CounteragentGroupDepartmentPatch.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = groupDepartments_.toBuilder();
              }
              groupDepartments_ = input.readMessage(Diadoc.Api.Proto.CounteragentGroups.CounteragentGroupToUpdateOuterClass.CounteragentGroupDepartmentPatch.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(groupDepartments_);
                groupDepartments_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Diadoc.Api.Proto.CounteragentGroups.CounteragentGroupToUpdateOuterClass.internal_static_Diadoc_Api_Proto_CounteragentGroups_CounteragentGroupToUpdate_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Diadoc.Api.Proto.CounteragentGroups.CounteragentGroupToUpdateOuterClass.internal_static_Diadoc_Api_Proto_CounteragentGroups_CounteragentGroupToUpdate_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Diadoc.Api.Proto.CounteragentGroups.CounteragentGroupToUpdateOuterClass.CounteragentGroupToUpdate.class, Diadoc.Api.Proto.CounteragentGroups.CounteragentGroupToUpdateOuterClass.CounteragentGroupToUpdate.Builder.class);
    }

    public static com.google.protobuf.Parser<CounteragentGroupToUpdate> PARSER =
        new com.google.protobuf.AbstractParser<CounteragentGroupToUpdate>() {
      public CounteragentGroupToUpdate parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CounteragentGroupToUpdate(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<CounteragentGroupToUpdate> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int NAME_FIELD_NUMBER = 1;
    private java.lang.Object name_;
    /**
     * <code>optional string Name = 1;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string Name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string Name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int GROUPDEPARTMENTS_FIELD_NUMBER = 2;
    private Diadoc.Api.Proto.CounteragentGroups.CounteragentGroupToUpdateOuterClass.CounteragentGroupDepartmentPatch groupDepartments_;
    /**
     * <code>optional .Diadoc.Api.Proto.CounteragentGroups.CounteragentGroupDepartmentPatch GroupDepartments = 2;</code>
     */
    public boolean hasGroupDepartments() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .Diadoc.Api.Proto.CounteragentGroups.CounteragentGroupDepartmentPatch GroupDepartments = 2;</code>
     */
    public Diadoc.Api.Proto.CounteragentGroups.CounteragentGroupToUpdateOuterClass.CounteragentGroupDepartmentPatch getGroupDepartments() {
      return groupDepartments_;
    }
    /**
     * <code>optional .Diadoc.Api.Proto.CounteragentGroups.CounteragentGroupDepartmentPatch GroupDepartments = 2;</code>
     */
    public Diadoc.Api.Proto.CounteragentGroups.CounteragentGroupToUpdateOuterClass.CounteragentGroupDepartmentPatchOrBuilder getGroupDepartmentsOrBuilder() {
      return groupDepartments_;
    }

    private void initFields() {
      name_ = "";
      groupDepartments_ = Diadoc.Api.Proto.CounteragentGroups.CounteragentGroupToUpdateOuterClass.CounteragentGroupDepartmentPatch.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (hasGroupDepartments()) {
        if (!getGroupDepartments().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, groupDepartments_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, groupDepartments_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static Diadoc.Api.Proto.CounteragentGroups.CounteragentGroupToUpdateOuterClass.CounteragentGroupToUpdate parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Diadoc.Api.Proto.CounteragentGroups.CounteragentGroupToUpdateOuterClass.CounteragentGroupToUpdate parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Diadoc.Api.Proto.CounteragentGroups.CounteragentGroupToUpdateOuterClass.CounteragentGroupToUpdate parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Diadoc.Api.Proto.CounteragentGroups.CounteragentGroupToUpdateOuterClass.CounteragentGroupToUpdate parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Diadoc.Api.Proto.CounteragentGroups.CounteragentGroupToUpdateOuterClass.CounteragentGroupToUpdate parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Diadoc.Api.Proto.CounteragentGroups.CounteragentGroupToUpdateOuterClass.CounteragentGroupToUpdate parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static Diadoc.Api.Proto.CounteragentGroups.CounteragentGroupToUpdateOuterClass.CounteragentGroupToUpdate parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static Diadoc.Api.Proto.CounteragentGroups.CounteragentGroupToUpdateOuterClass.CounteragentGroupToUpdate parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static Diadoc.Api.Proto.CounteragentGroups.CounteragentGroupToUpdateOuterClass.CounteragentGroupToUpdate parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Diadoc.Api.Proto.CounteragentGroups.CounteragentGroupToUpdateOuterClass.CounteragentGroupToUpdate parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Diadoc.Api.Proto.CounteragentGroups.CounteragentGroupToUpdateOuterClass.CounteragentGroupToUpdate prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Diadoc.Api.Proto.CounteragentGroups.CounteragentGroupToUpdate}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Diadoc.Api.Proto.CounteragentGroups.CounteragentGroupToUpdate)
        Diadoc.Api.Proto.CounteragentGroups.CounteragentGroupToUpdateOuterClass.CounteragentGroupToUpdateOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Diadoc.Api.Proto.CounteragentGroups.CounteragentGroupToUpdateOuterClass.internal_static_Diadoc_Api_Proto_CounteragentGroups_CounteragentGroupToUpdate_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Diadoc.Api.Proto.CounteragentGroups.CounteragentGroupToUpdateOuterClass.internal_static_Diadoc_Api_Proto_CounteragentGroups_CounteragentGroupToUpdate_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Diadoc.Api.Proto.CounteragentGroups.CounteragentGroupToUpdateOuterClass.CounteragentGroupToUpdate.class, Diadoc.Api.Proto.CounteragentGroups.CounteragentGroupToUpdateOuterClass.CounteragentGroupToUpdate.Builder.class);
      }

      // Construct using Diadoc.Api.Proto.CounteragentGroups.CounteragentGroupToUpdateOuterClass.CounteragentGroupToUpdate.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getGroupDepartmentsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        if (groupDepartmentsBuilder_ == null) {
          groupDepartments_ = Diadoc.Api.Proto.CounteragentGroups.CounteragentGroupToUpdateOuterClass.CounteragentGroupDepartmentPatch.getDefaultInstance();
        } else {
          groupDepartmentsBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Diadoc.Api.Proto.CounteragentGroups.CounteragentGroupToUpdateOuterClass.internal_static_Diadoc_Api_Proto_CounteragentGroups_CounteragentGroupToUpdate_descriptor;
      }

      public Diadoc.Api.Proto.CounteragentGroups.CounteragentGroupToUpdateOuterClass.CounteragentGroupToUpdate getDefaultInstanceForType() {
        return Diadoc.Api.Proto.CounteragentGroups.CounteragentGroupToUpdateOuterClass.CounteragentGroupToUpdate.getDefaultInstance();
      }

      public Diadoc.Api.Proto.CounteragentGroups.CounteragentGroupToUpdateOuterClass.CounteragentGroupToUpdate build() {
        Diadoc.Api.Proto.CounteragentGroups.CounteragentGroupToUpdateOuterClass.CounteragentGroupToUpdate result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Diadoc.Api.Proto.CounteragentGroups.CounteragentGroupToUpdateOuterClass.CounteragentGroupToUpdate buildPartial() {
        Diadoc.Api.Proto.CounteragentGroups.CounteragentGroupToUpdateOuterClass.CounteragentGroupToUpdate result = new Diadoc.Api.Proto.CounteragentGroups.CounteragentGroupToUpdateOuterClass.CounteragentGroupToUpdate(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (groupDepartmentsBuilder_ == null) {
          result.groupDepartments_ = groupDepartments_;
        } else {
          result.groupDepartments_ = groupDepartmentsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Diadoc.Api.Proto.CounteragentGroups.CounteragentGroupToUpdateOuterClass.CounteragentGroupToUpdate) {
          return mergeFrom((Diadoc.Api.Proto.CounteragentGroups.CounteragentGroupToUpdateOuterClass.CounteragentGroupToUpdate)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Diadoc.Api.Proto.CounteragentGroups.CounteragentGroupToUpdateOuterClass.CounteragentGroupToUpdate other) {
        if (other == Diadoc.Api.Proto.CounteragentGroups.CounteragentGroupToUpdateOuterClass.CounteragentGroupToUpdate.getDefaultInstance()) return this;
        if (other.hasName()) {
          bitField0_ |= 0x00000001;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasGroupDepartments()) {
          mergeGroupDepartments(other.getGroupDepartments());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (hasGroupDepartments()) {
          if (!getGroupDepartments().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Diadoc.Api.Proto.CounteragentGroups.CounteragentGroupToUpdateOuterClass.CounteragentGroupToUpdate parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Diadoc.Api.Proto.CounteragentGroups.CounteragentGroupToUpdateOuterClass.CounteragentGroupToUpdate) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object name_ = "";
      /**
       * <code>optional string Name = 1;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string Name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string Name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string Name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string Name = 1;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string Name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }

      private Diadoc.Api.Proto.CounteragentGroups.CounteragentGroupToUpdateOuterClass.CounteragentGroupDepartmentPatch groupDepartments_ = Diadoc.Api.Proto.CounteragentGroups.CounteragentGroupToUpdateOuterClass.CounteragentGroupDepartmentPatch.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          Diadoc.Api.Proto.CounteragentGroups.CounteragentGroupToUpdateOuterClass.CounteragentGroupDepartmentPatch, Diadoc.Api.Proto.CounteragentGroups.CounteragentGroupToUpdateOuterClass.CounteragentGroupDepartmentPatch.Builder, Diadoc.Api.Proto.CounteragentGroups.CounteragentGroupToUpdateOuterClass.CounteragentGroupDepartmentPatchOrBuilder> groupDepartmentsBuilder_;
      /**
       * <code>optional .Diadoc.Api.Proto.CounteragentGroups.CounteragentGroupDepartmentPatch GroupDepartments = 2;</code>
       */
      public boolean hasGroupDepartments() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .Diadoc.Api.Proto.CounteragentGroups.CounteragentGroupDepartmentPatch GroupDepartments = 2;</code>
       */
      public Diadoc.Api.Proto.CounteragentGroups.CounteragentGroupToUpdateOuterClass.CounteragentGroupDepartmentPatch getGroupDepartments() {
        if (groupDepartmentsBuilder_ == null) {
          return groupDepartments_;
        } else {
          return groupDepartmentsBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .Diadoc.Api.Proto.CounteragentGroups.CounteragentGroupDepartmentPatch GroupDepartments = 2;</code>
       */
      public Builder setGroupDepartments(Diadoc.Api.Proto.CounteragentGroups.CounteragentGroupToUpdateOuterClass.CounteragentGroupDepartmentPatch value) {
        if (groupDepartmentsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          groupDepartments_ = value;
          onChanged();
        } else {
          groupDepartmentsBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .Diadoc.Api.Proto.CounteragentGroups.CounteragentGroupDepartmentPatch GroupDepartments = 2;</code>
       */
      public Builder setGroupDepartments(
          Diadoc.Api.Proto.CounteragentGroups.CounteragentGroupToUpdateOuterClass.CounteragentGroupDepartmentPatch.Builder builderForValue) {
        if (groupDepartmentsBuilder_ == null) {
          groupDepartments_ = builderForValue.build();
          onChanged();
        } else {
          groupDepartmentsBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .Diadoc.Api.Proto.CounteragentGroups.CounteragentGroupDepartmentPatch GroupDepartments = 2;</code>
       */
      public Builder mergeGroupDepartments(Diadoc.Api.Proto.CounteragentGroups.CounteragentGroupToUpdateOuterClass.CounteragentGroupDepartmentPatch value) {
        if (groupDepartmentsBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              groupDepartments_ != Diadoc.Api.Proto.CounteragentGroups.CounteragentGroupToUpdateOuterClass.CounteragentGroupDepartmentPatch.getDefaultInstance()) {
            groupDepartments_ =
              Diadoc.Api.Proto.CounteragentGroups.CounteragentGroupToUpdateOuterClass.CounteragentGroupDepartmentPatch.newBuilder(groupDepartments_).mergeFrom(value).buildPartial();
          } else {
            groupDepartments_ = value;
          }
          onChanged();
        } else {
          groupDepartmentsBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .Diadoc.Api.Proto.CounteragentGroups.CounteragentGroupDepartmentPatch GroupDepartments = 2;</code>
       */
      public Builder clearGroupDepartments() {
        if (groupDepartmentsBuilder_ == null) {
          groupDepartments_ = Diadoc.Api.Proto.CounteragentGroups.CounteragentGroupToUpdateOuterClass.CounteragentGroupDepartmentPatch.getDefaultInstance();
          onChanged();
        } else {
          groupDepartmentsBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>optional .Diadoc.Api.Proto.CounteragentGroups.CounteragentGroupDepartmentPatch GroupDepartments = 2;</code>
       */
      public Diadoc.Api.Proto.CounteragentGroups.CounteragentGroupToUpdateOuterClass.CounteragentGroupDepartmentPatch.Builder getGroupDepartmentsBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getGroupDepartmentsFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .Diadoc.Api.Proto.CounteragentGroups.CounteragentGroupDepartmentPatch GroupDepartments = 2;</code>
       */
      public Diadoc.Api.Proto.CounteragentGroups.CounteragentGroupToUpdateOuterClass.CounteragentGroupDepartmentPatchOrBuilder getGroupDepartmentsOrBuilder() {
        if (groupDepartmentsBuilder_ != null) {
          return groupDepartmentsBuilder_.getMessageOrBuilder();
        } else {
          return groupDepartments_;
        }
      }
      /**
       * <code>optional .Diadoc.Api.Proto.CounteragentGroups.CounteragentGroupDepartmentPatch GroupDepartments = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          Diadoc.Api.Proto.CounteragentGroups.CounteragentGroupToUpdateOuterClass.CounteragentGroupDepartmentPatch, Diadoc.Api.Proto.CounteragentGroups.CounteragentGroupToUpdateOuterClass.CounteragentGroupDepartmentPatch.Builder, Diadoc.Api.Proto.CounteragentGroups.CounteragentGroupToUpdateOuterClass.CounteragentGroupDepartmentPatchOrBuilder> 
          getGroupDepartmentsFieldBuilder() {
        if (groupDepartmentsBuilder_ == null) {
          groupDepartmentsBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              Diadoc.Api.Proto.CounteragentGroups.CounteragentGroupToUpdateOuterClass.CounteragentGroupDepartmentPatch, Diadoc.Api.Proto.CounteragentGroups.CounteragentGroupToUpdateOuterClass.CounteragentGroupDepartmentPatch.Builder, Diadoc.Api.Proto.CounteragentGroups.CounteragentGroupToUpdateOuterClass.CounteragentGroupDepartmentPatchOrBuilder>(
                  getGroupDepartments(),
                  getParentForChildren(),
                  isClean());
          groupDepartments_ = null;
        }
        return groupDepartmentsBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:Diadoc.Api.Proto.CounteragentGroups.CounteragentGroupToUpdate)
    }

    static {
      defaultInstance = new CounteragentGroupToUpdate(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Diadoc.Api.Proto.CounteragentGroups.CounteragentGroupToUpdate)
  }

  public interface CounteragentGroupDepartmentPatchOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Diadoc.Api.Proto.CounteragentGroups.CounteragentGroupDepartmentPatch)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required bool AnyDepartment = 1;</code>
     */
    boolean hasAnyDepartment();
    /**
     * <code>required bool AnyDepartment = 1;</code>
     */
    boolean getAnyDepartment();

    /**
     * <code>optional .Diadoc.Api.Proto.CounteragentGroups.DepartmentsInGroup Departments = 2;</code>
     */
    boolean hasDepartments();
    /**
     * <code>optional .Diadoc.Api.Proto.CounteragentGroups.DepartmentsInGroup Departments = 2;</code>
     */
    Diadoc.Api.Proto.CounteragentGroups.DepartmentsInGroupOuterClass.DepartmentsInGroup getDepartments();
    /**
     * <code>optional .Diadoc.Api.Proto.CounteragentGroups.DepartmentsInGroup Departments = 2;</code>
     */
    Diadoc.Api.Proto.CounteragentGroups.DepartmentsInGroupOuterClass.DepartmentsInGroupOrBuilder getDepartmentsOrBuilder();
  }
  /**
   * Protobuf type {@code Diadoc.Api.Proto.CounteragentGroups.CounteragentGroupDepartmentPatch}
   */
  public static final class CounteragentGroupDepartmentPatch extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Diadoc.Api.Proto.CounteragentGroups.CounteragentGroupDepartmentPatch)
      CounteragentGroupDepartmentPatchOrBuilder {
    // Use CounteragentGroupDepartmentPatch.newBuilder() to construct.
    private CounteragentGroupDepartmentPatch(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private CounteragentGroupDepartmentPatch(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final CounteragentGroupDepartmentPatch defaultInstance;
    public static CounteragentGroupDepartmentPatch getDefaultInstance() {
      return defaultInstance;
    }

    public CounteragentGroupDepartmentPatch getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private CounteragentGroupDepartmentPatch(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              anyDepartment_ = input.readBool();
              break;
            }
            case 18: {
              Diadoc.Api.Proto.CounteragentGroups.DepartmentsInGroupOuterClass.DepartmentsInGroup.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = departments_.toBuilder();
              }
              departments_ = input.readMessage(Diadoc.Api.Proto.CounteragentGroups.DepartmentsInGroupOuterClass.DepartmentsInGroup.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(departments_);
                departments_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Diadoc.Api.Proto.CounteragentGroups.CounteragentGroupToUpdateOuterClass.internal_static_Diadoc_Api_Proto_CounteragentGroups_CounteragentGroupDepartmentPatch_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Diadoc.Api.Proto.CounteragentGroups.CounteragentGroupToUpdateOuterClass.internal_static_Diadoc_Api_Proto_CounteragentGroups_CounteragentGroupDepartmentPatch_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Diadoc.Api.Proto.CounteragentGroups.CounteragentGroupToUpdateOuterClass.CounteragentGroupDepartmentPatch.class, Diadoc.Api.Proto.CounteragentGroups.CounteragentGroupToUpdateOuterClass.CounteragentGroupDepartmentPatch.Builder.class);
    }

    public static com.google.protobuf.Parser<CounteragentGroupDepartmentPatch> PARSER =
        new com.google.protobuf.AbstractParser<CounteragentGroupDepartmentPatch>() {
      public CounteragentGroupDepartmentPatch parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CounteragentGroupDepartmentPatch(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<CounteragentGroupDepartmentPatch> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int ANYDEPARTMENT_FIELD_NUMBER = 1;
    private boolean anyDepartment_;
    /**
     * <code>required bool AnyDepartment = 1;</code>
     */
    public boolean hasAnyDepartment() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required bool AnyDepartment = 1;</code>
     */
    public boolean getAnyDepartment() {
      return anyDepartment_;
    }

    public static final int DEPARTMENTS_FIELD_NUMBER = 2;
    private Diadoc.Api.Proto.CounteragentGroups.DepartmentsInGroupOuterClass.DepartmentsInGroup departments_;
    /**
     * <code>optional .Diadoc.Api.Proto.CounteragentGroups.DepartmentsInGroup Departments = 2;</code>
     */
    public boolean hasDepartments() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .Diadoc.Api.Proto.CounteragentGroups.DepartmentsInGroup Departments = 2;</code>
     */
    public Diadoc.Api.Proto.CounteragentGroups.DepartmentsInGroupOuterClass.DepartmentsInGroup getDepartments() {
      return departments_;
    }
    /**
     * <code>optional .Diadoc.Api.Proto.CounteragentGroups.DepartmentsInGroup Departments = 2;</code>
     */
    public Diadoc.Api.Proto.CounteragentGroups.DepartmentsInGroupOuterClass.DepartmentsInGroupOrBuilder getDepartmentsOrBuilder() {
      return departments_;
    }

    private void initFields() {
      anyDepartment_ = false;
      departments_ = Diadoc.Api.Proto.CounteragentGroups.DepartmentsInGroupOuterClass.DepartmentsInGroup.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasAnyDepartment()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBool(1, anyDepartment_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, departments_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, anyDepartment_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, departments_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static Diadoc.Api.Proto.CounteragentGroups.CounteragentGroupToUpdateOuterClass.CounteragentGroupDepartmentPatch parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Diadoc.Api.Proto.CounteragentGroups.CounteragentGroupToUpdateOuterClass.CounteragentGroupDepartmentPatch parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Diadoc.Api.Proto.CounteragentGroups.CounteragentGroupToUpdateOuterClass.CounteragentGroupDepartmentPatch parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Diadoc.Api.Proto.CounteragentGroups.CounteragentGroupToUpdateOuterClass.CounteragentGroupDepartmentPatch parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Diadoc.Api.Proto.CounteragentGroups.CounteragentGroupToUpdateOuterClass.CounteragentGroupDepartmentPatch parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Diadoc.Api.Proto.CounteragentGroups.CounteragentGroupToUpdateOuterClass.CounteragentGroupDepartmentPatch parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static Diadoc.Api.Proto.CounteragentGroups.CounteragentGroupToUpdateOuterClass.CounteragentGroupDepartmentPatch parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static Diadoc.Api.Proto.CounteragentGroups.CounteragentGroupToUpdateOuterClass.CounteragentGroupDepartmentPatch parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static Diadoc.Api.Proto.CounteragentGroups.CounteragentGroupToUpdateOuterClass.CounteragentGroupDepartmentPatch parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Diadoc.Api.Proto.CounteragentGroups.CounteragentGroupToUpdateOuterClass.CounteragentGroupDepartmentPatch parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Diadoc.Api.Proto.CounteragentGroups.CounteragentGroupToUpdateOuterClass.CounteragentGroupDepartmentPatch prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Diadoc.Api.Proto.CounteragentGroups.CounteragentGroupDepartmentPatch}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Diadoc.Api.Proto.CounteragentGroups.CounteragentGroupDepartmentPatch)
        Diadoc.Api.Proto.CounteragentGroups.CounteragentGroupToUpdateOuterClass.CounteragentGroupDepartmentPatchOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Diadoc.Api.Proto.CounteragentGroups.CounteragentGroupToUpdateOuterClass.internal_static_Diadoc_Api_Proto_CounteragentGroups_CounteragentGroupDepartmentPatch_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Diadoc.Api.Proto.CounteragentGroups.CounteragentGroupToUpdateOuterClass.internal_static_Diadoc_Api_Proto_CounteragentGroups_CounteragentGroupDepartmentPatch_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Diadoc.Api.Proto.CounteragentGroups.CounteragentGroupToUpdateOuterClass.CounteragentGroupDepartmentPatch.class, Diadoc.Api.Proto.CounteragentGroups.CounteragentGroupToUpdateOuterClass.CounteragentGroupDepartmentPatch.Builder.class);
      }

      // Construct using Diadoc.Api.Proto.CounteragentGroups.CounteragentGroupToUpdateOuterClass.CounteragentGroupDepartmentPatch.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getDepartmentsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        anyDepartment_ = false;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (departmentsBuilder_ == null) {
          departments_ = Diadoc.Api.Proto.CounteragentGroups.DepartmentsInGroupOuterClass.DepartmentsInGroup.getDefaultInstance();
        } else {
          departmentsBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Diadoc.Api.Proto.CounteragentGroups.CounteragentGroupToUpdateOuterClass.internal_static_Diadoc_Api_Proto_CounteragentGroups_CounteragentGroupDepartmentPatch_descriptor;
      }

      public Diadoc.Api.Proto.CounteragentGroups.CounteragentGroupToUpdateOuterClass.CounteragentGroupDepartmentPatch getDefaultInstanceForType() {
        return Diadoc.Api.Proto.CounteragentGroups.CounteragentGroupToUpdateOuterClass.CounteragentGroupDepartmentPatch.getDefaultInstance();
      }

      public Diadoc.Api.Proto.CounteragentGroups.CounteragentGroupToUpdateOuterClass.CounteragentGroupDepartmentPatch build() {
        Diadoc.Api.Proto.CounteragentGroups.CounteragentGroupToUpdateOuterClass.CounteragentGroupDepartmentPatch result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Diadoc.Api.Proto.CounteragentGroups.CounteragentGroupToUpdateOuterClass.CounteragentGroupDepartmentPatch buildPartial() {
        Diadoc.Api.Proto.CounteragentGroups.CounteragentGroupToUpdateOuterClass.CounteragentGroupDepartmentPatch result = new Diadoc.Api.Proto.CounteragentGroups.CounteragentGroupToUpdateOuterClass.CounteragentGroupDepartmentPatch(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.anyDepartment_ = anyDepartment_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (departmentsBuilder_ == null) {
          result.departments_ = departments_;
        } else {
          result.departments_ = departmentsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Diadoc.Api.Proto.CounteragentGroups.CounteragentGroupToUpdateOuterClass.CounteragentGroupDepartmentPatch) {
          return mergeFrom((Diadoc.Api.Proto.CounteragentGroups.CounteragentGroupToUpdateOuterClass.CounteragentGroupDepartmentPatch)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Diadoc.Api.Proto.CounteragentGroups.CounteragentGroupToUpdateOuterClass.CounteragentGroupDepartmentPatch other) {
        if (other == Diadoc.Api.Proto.CounteragentGroups.CounteragentGroupToUpdateOuterClass.CounteragentGroupDepartmentPatch.getDefaultInstance()) return this;
        if (other.hasAnyDepartment()) {
          setAnyDepartment(other.getAnyDepartment());
        }
        if (other.hasDepartments()) {
          mergeDepartments(other.getDepartments());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasAnyDepartment()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Diadoc.Api.Proto.CounteragentGroups.CounteragentGroupToUpdateOuterClass.CounteragentGroupDepartmentPatch parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Diadoc.Api.Proto.CounteragentGroups.CounteragentGroupToUpdateOuterClass.CounteragentGroupDepartmentPatch) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private boolean anyDepartment_ ;
      /**
       * <code>required bool AnyDepartment = 1;</code>
       */
      public boolean hasAnyDepartment() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required bool AnyDepartment = 1;</code>
       */
      public boolean getAnyDepartment() {
        return anyDepartment_;
      }
      /**
       * <code>required bool AnyDepartment = 1;</code>
       */
      public Builder setAnyDepartment(boolean value) {
        bitField0_ |= 0x00000001;
        anyDepartment_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bool AnyDepartment = 1;</code>
       */
      public Builder clearAnyDepartment() {
        bitField0_ = (bitField0_ & ~0x00000001);
        anyDepartment_ = false;
        onChanged();
        return this;
      }

      private Diadoc.Api.Proto.CounteragentGroups.DepartmentsInGroupOuterClass.DepartmentsInGroup departments_ = Diadoc.Api.Proto.CounteragentGroups.DepartmentsInGroupOuterClass.DepartmentsInGroup.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          Diadoc.Api.Proto.CounteragentGroups.DepartmentsInGroupOuterClass.DepartmentsInGroup, Diadoc.Api.Proto.CounteragentGroups.DepartmentsInGroupOuterClass.DepartmentsInGroup.Builder, Diadoc.Api.Proto.CounteragentGroups.DepartmentsInGroupOuterClass.DepartmentsInGroupOrBuilder> departmentsBuilder_;
      /**
       * <code>optional .Diadoc.Api.Proto.CounteragentGroups.DepartmentsInGroup Departments = 2;</code>
       */
      public boolean hasDepartments() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .Diadoc.Api.Proto.CounteragentGroups.DepartmentsInGroup Departments = 2;</code>
       */
      public Diadoc.Api.Proto.CounteragentGroups.DepartmentsInGroupOuterClass.DepartmentsInGroup getDepartments() {
        if (departmentsBuilder_ == null) {
          return departments_;
        } else {
          return departmentsBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .Diadoc.Api.Proto.CounteragentGroups.DepartmentsInGroup Departments = 2;</code>
       */
      public Builder setDepartments(Diadoc.Api.Proto.CounteragentGroups.DepartmentsInGroupOuterClass.DepartmentsInGroup value) {
        if (departmentsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          departments_ = value;
          onChanged();
        } else {
          departmentsBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .Diadoc.Api.Proto.CounteragentGroups.DepartmentsInGroup Departments = 2;</code>
       */
      public Builder setDepartments(
          Diadoc.Api.Proto.CounteragentGroups.DepartmentsInGroupOuterClass.DepartmentsInGroup.Builder builderForValue) {
        if (departmentsBuilder_ == null) {
          departments_ = builderForValue.build();
          onChanged();
        } else {
          departmentsBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .Diadoc.Api.Proto.CounteragentGroups.DepartmentsInGroup Departments = 2;</code>
       */
      public Builder mergeDepartments(Diadoc.Api.Proto.CounteragentGroups.DepartmentsInGroupOuterClass.DepartmentsInGroup value) {
        if (departmentsBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              departments_ != Diadoc.Api.Proto.CounteragentGroups.DepartmentsInGroupOuterClass.DepartmentsInGroup.getDefaultInstance()) {
            departments_ =
              Diadoc.Api.Proto.CounteragentGroups.DepartmentsInGroupOuterClass.DepartmentsInGroup.newBuilder(departments_).mergeFrom(value).buildPartial();
          } else {
            departments_ = value;
          }
          onChanged();
        } else {
          departmentsBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .Diadoc.Api.Proto.CounteragentGroups.DepartmentsInGroup Departments = 2;</code>
       */
      public Builder clearDepartments() {
        if (departmentsBuilder_ == null) {
          departments_ = Diadoc.Api.Proto.CounteragentGroups.DepartmentsInGroupOuterClass.DepartmentsInGroup.getDefaultInstance();
          onChanged();
        } else {
          departmentsBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>optional .Diadoc.Api.Proto.CounteragentGroups.DepartmentsInGroup Departments = 2;</code>
       */
      public Diadoc.Api.Proto.CounteragentGroups.DepartmentsInGroupOuterClass.DepartmentsInGroup.Builder getDepartmentsBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getDepartmentsFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .Diadoc.Api.Proto.CounteragentGroups.DepartmentsInGroup Departments = 2;</code>
       */
      public Diadoc.Api.Proto.CounteragentGroups.DepartmentsInGroupOuterClass.DepartmentsInGroupOrBuilder getDepartmentsOrBuilder() {
        if (departmentsBuilder_ != null) {
          return departmentsBuilder_.getMessageOrBuilder();
        } else {
          return departments_;
        }
      }
      /**
       * <code>optional .Diadoc.Api.Proto.CounteragentGroups.DepartmentsInGroup Departments = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          Diadoc.Api.Proto.CounteragentGroups.DepartmentsInGroupOuterClass.DepartmentsInGroup, Diadoc.Api.Proto.CounteragentGroups.DepartmentsInGroupOuterClass.DepartmentsInGroup.Builder, Diadoc.Api.Proto.CounteragentGroups.DepartmentsInGroupOuterClass.DepartmentsInGroupOrBuilder> 
          getDepartmentsFieldBuilder() {
        if (departmentsBuilder_ == null) {
          departmentsBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              Diadoc.Api.Proto.CounteragentGroups.DepartmentsInGroupOuterClass.DepartmentsInGroup, Diadoc.Api.Proto.CounteragentGroups.DepartmentsInGroupOuterClass.DepartmentsInGroup.Builder, Diadoc.Api.Proto.CounteragentGroups.DepartmentsInGroupOuterClass.DepartmentsInGroupOrBuilder>(
                  getDepartments(),
                  getParentForChildren(),
                  isClean());
          departments_ = null;
        }
        return departmentsBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:Diadoc.Api.Proto.CounteragentGroups.CounteragentGroupDepartmentPatch)
    }

    static {
      defaultInstance = new CounteragentGroupDepartmentPatch(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Diadoc.Api.Proto.CounteragentGroups.CounteragentGroupDepartmentPatch)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Diadoc_Api_Proto_CounteragentGroups_CounteragentGroupToUpdate_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Diadoc_Api_Proto_CounteragentGroups_CounteragentGroupToUpdate_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Diadoc_Api_Proto_CounteragentGroups_CounteragentGroupDepartmentPatch_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Diadoc_Api_Proto_CounteragentGroups_CounteragentGroupDepartmentPatch_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n2CounteragentGroups/CounteragentGroupTo" +
      "Update.proto\022#Diadoc.Api.Proto.Counterag" +
      "entGroups\032+CounteragentGroups/Department" +
      "sInGroup.proto\"\212\001\n\031CounteragentGroupToUp" +
      "date\022\014\n\004Name\030\001 \001(\t\022_\n\020GroupDepartments\030\002" +
      " \001(\0132E.Diadoc.Api.Proto.CounteragentGrou" +
      "ps.CounteragentGroupDepartmentPatch\"\207\001\n " +
      "CounteragentGroupDepartmentPatch\022\025\n\rAnyD" +
      "epartment\030\001 \002(\010\022L\n\013Departments\030\002 \001(\01327.D" +
      "iadoc.Api.Proto.CounteragentGroups.Depar",
      "tmentsInGroup"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          Diadoc.Api.Proto.CounteragentGroups.DepartmentsInGroupOuterClass.getDescriptor(),
        }, assigner);
    internal_static_Diadoc_Api_Proto_CounteragentGroups_CounteragentGroupToUpdate_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Diadoc_Api_Proto_CounteragentGroups_CounteragentGroupToUpdate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Diadoc_Api_Proto_CounteragentGroups_CounteragentGroupToUpdate_descriptor,
        new java.lang.String[] { "Name", "GroupDepartments", });
    internal_static_Diadoc_Api_Proto_CounteragentGroups_CounteragentGroupDepartmentPatch_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Diadoc_Api_Proto_CounteragentGroups_CounteragentGroupDepartmentPatch_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Diadoc_Api_Proto_CounteragentGroups_CounteragentGroupDepartmentPatch_descriptor,
        new java.lang.String[] { "AnyDepartment", "Departments", });
    Diadoc.Api.Proto.CounteragentGroups.DepartmentsInGroupOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
